modLoader="javafml"
loaderVersion="[47,)"
license="LGPLv3"

[[mods]]
modId="taczworkshop"
version="${file.jarVersion}"
displayName="TACZ Workshop"
authors="XYAT"
description='''
TACZ firearm, attachment, ammunition, melee, supply, and recipe editing tools.
'''

[[dependencies.taczworkshop]]
modId="forge"
mandatory=true
versionRange="[47.4.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.taczworkshop]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.taczworkshop]]
modId="kineticcore"
mandatory=true
versionRange="[26.9.20,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taczworkshop]]
modId="tacz"
mandatory=true
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taczworkshop]]
modId="sophisticatedbackpacks"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taczworkshop]]
modId="sophisticatedcore"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
